basic.forever(function () {
    if (input.lightLevel() > 15) {
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(392, music.beat(BeatFraction.Half))
        music.playTone(440, music.beat(BeatFraction.Whole))
        music.playTone(392, music.beat(BeatFraction.Whole))
        music.playTone(523, music.beat(BeatFraction.Whole))
        music.playTone(494, music.beat(BeatFraction.Whole))
        basic.pause(1000)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(392, music.beat(BeatFraction.Half))
        music.playTone(440, music.beat(BeatFraction.Whole))
        music.playTone(392, music.beat(BeatFraction.Whole))
        music.playTone(587, music.beat(BeatFraction.Whole))
        music.playTone(523, music.beat(BeatFraction.Whole))
        basic.pause(1000)
        music.playTone(392, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(392, music.beat(BeatFraction.Half))
        music.playTone(784, music.beat(BeatFraction.Whole))
        music.playTone(659, music.beat(BeatFraction.Whole))
        music.playTone(523, music.beat(BeatFraction.Whole))
        music.playTone(494, music.beat(BeatFraction.Whole))
        music.playTone(440, music.beat(BeatFraction.Whole))
        basic.pause(1000)
        music.playTone(698, music.beat(BeatFraction.Half))
        basic.pause(50)
        music.playTone(698, music.beat(BeatFraction.Half))
        music.playTone(659, music.beat(BeatFraction.Whole))
        music.playTone(523, music.beat(BeatFraction.Whole))
        music.playTone(587, music.beat(BeatFraction.Whole))
        music.playTone(523, music.beat(BeatFraction.Whole))
    }
    if (input.lightLevel() < 5) {
        music.stopMelody(MelodyStopOptions.All)
    }
})
